ARDUINO_DIR = /home/pi/Downloads/arduino-1.8.13/
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
AVRDUDE = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
AVRDUDE_ARD_BAUDRATE = 57600
BOARD_TAG = atmega328p_bare
BOARDS_TXT = ./bare_boards.txt

# USER_LIB_PATH = ./lib
# ARDUINO_LIBS = Wire SPI SoftwareSerial RadioHead-1.81
# AVRDUDE_CONF = ./avrdude_gpio.conf
# BOARD_TAG = atmega328p_pi

MONITOR_PORT = /dev/ttyUSB0
MONITOR_BAUDRATE = 9600

include $(ARDMK_DIR)/Arduino.mk
